# Globals
sudo: false
language: go
go:
  - 1.13.x
env:
  global:
    - VERSION=$(echo ${TRAVIS_BRANCH} | sed "s/\//_/g")
    - OUTPUT="bettercap"
cache:
  apt: true

# Includes
linux_deps: &linux_deps
  os: linux
  dist: bionic
  addons:
    apt:
      packages:
        - p7zip-full
        - libpcap-dev
        - libnetfilter-queue-dev
        - libusb-1.0-0-dev
      update: true

finish: &finish
  after_success:
    - file "${OUTPUT}"
    - openssl dgst -sha256 "${OUTPUT}" | tee bettercap_${TARGET_OS}_${TARGET_ARCH}_${VERSION}.sha256
    - 7z a "bettercap_${TARGET_OS}_${TARGET_ARCH}_${VERSION}.zip" "${OUTPUT}" "bettercap_${TARGET_OS}_${TARGET_ARCH}_${VERSION}.sha256"
    - ls -la bettercap*

cross_deps: &cross_deps
  <<: *linux_deps
  before_install:
    - wget --show-progress -qcO "qemu.deb" "https://debian.grena.ge/debian/pool/main/q/qemu/qemu-user-static_4.2-3_amd64.deb"
    - sudo dpkg -i "qemu.deb"

normal_install: &normal_install
  install:
    - make -e TARGET="${OUTPUT}"
  <<: *finish

cross_install: &cross_install
  install:
    - sudo builder/arm_builder.sh bettercap make -e TARGET="${OUTPUT}"
  <<: *finish

# Tasks
matrix:
  include:
    - name: Linux - amd64
      if: tag IS present
      arch: amd64
      env:
        - TARGET_OS=linux
        - TARGET_ARCH=amd64
      <<: *linux_deps
      <<: *normal_install

    - name: Linux - aarch64
      if: tag IS present
      arch: arm64
      env:
        - TARGET_OS=linux
        - TARGET_ARCH=aarch64
        - GEM_HOME=~/.ruby
        - PATH=$PATH:~/.ruby/bin
      <<: *linux_deps
      <<: *normal_install
      before_install:
        - mkdir -p ~/.ruby

    - name: Linux - armhf
      if: tag IS present
      language: minimal
      arch: amd64
      env:
        - TARGET_OS=linux
        - TARGET_ARCH=armhf
      <<: *cross_deps
      <<: *cross_install

    - name: OSX - amd64
      if: tag IS present
      os: osx
      arch: amd64
      addons:
        homebrew:
          packages:
            - libpcap
            - libusb
            - p7zip
          update: true
      env:
        - TARGET_OS=darwin
        - TARGET_ARCH=amd64
        - PATH="/usr/local/opt/libpcap/bin:$PATH"
        - LDFLAGS="-L/usr/local/opt/libpcap/lib $LDFLAGS"
        - CPPFLAGS="-I/usr/local/opt/libpcap/include $CPPFLAGS"
        - PKG_CONFIG_PATH="/usr/local/opt/libpcap/lib/pkgconfig:$PKG_CONFIG_PATH"
      <<: *normal_install

    - name: Windows - amd64
      if: tag IS present
      os: windows
      arch: amd64
      env:
        - TARGET_OS=windows
        - TARGET_ARCH=amd64
        - PKG_CONFIG_PATH="c:/pkg-config"
        - OUTPUT=bettercap.exe
        - CGO_CFLAGS="-I/c/npcap/Include -I/c/libusb/include/libusb-1.0"
        - CGO_LDFLAGS="-L/c/npcap/Lib/x64 -L/c/libusb/MinGW64/static"
      before_install:
        - choco install openssl.light -y
        - choco install make -y
        - choco install 7zip -y
        - choco install pkgconfiglite -y
        - mkdir /c/pkg-config
        - choco install zadig -y
        - curl -L "https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z"
          -o "/c/libusb.7z"
        - 7z x -y "/c/libusb.7z" -o"/c/libusb"
        - choco install npcap --version 0.86 -y
        - curl -L "https://nmap.org/npcap/dist/npcap-sdk-1.03.zip" -o "c:/npcap.zip"
        - 7z x -y "/c/npcap.zip" -o"/c/npcap"
        - cp builder/libusb.pc /c/pkg-config/libusb.pc
        - cp builder/libusb.pc /c/pkg-config/libusb-1.0.pc
      <<: *normal_install

    - name: Linux - tests
      if: tag IS blank
      os: linux
      arch: amd64
      allow_failures:
        - go: master
      fast_finish: true
      <<: *linux_deps
      script:
        - env GO111MODULE=on make test
      after_success:
        - base <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: N9XZMjnpgy/UfeNkuAzIXuDzhx40mwA20CNjqMV8GysSXgnZAXuqKMrTOC67zXGRGTitzc+nw/dkxnfNkcWIWZefOkGHt3mceqiYz2PIn/mRs7TrxYRPinUoTGkfVgJcxiK2LW7xJnin9Lrc60/w94neRXmjPM/0r0VPCdWviCtE/HFzEekcudnZLztjJewa2TFhAe96j+Hfgt9sLNESPJy8iChTqJwXgRV906AX9/V/2X39uAFm09tizQfryNXIDM6rf4j3j4NB6l6/0FrUrWMbhz88lwyPH/c3h0XpvebSuXnGRNtltedpdTsGW/ER+ELKJasiI7aTYqN0lHjeQ/DYk4Wdd6KbLEK2O4NqTkesWzkBPgD6gr7GRkMEr90DoQlFD+N5fPUPCOx0w9DMZHAcpPle4FpZSQWXt4U8gQOXfSIkyfgpScwqaVS8D+6t+7+uOh5O7vCMZmbZ15Y/dxu8oJ2X9vh8JcV5aHzJp+/51jg3FlSbtNRBY96qKBWwdAt0BiJ9JA/OiGG/XZepexMBCm1cFD6jP8S814BhIBDN8UrlUQjC4RU6zbsG8K5hDg1c+gTFkoL1bpvhpSX/zO+OkWa84tCgJK4qXDVWBn4/X6eT8ElwtRuBY2CO9NGGMgZyZEoB8OtGZwbAErxFurKMTQzfg/S3zK9zx+GyRos=
  skip_cleanup: true
  file_glob: true
  file:
    - bettercap_*.zip
    - bettercap_*.sha256
  on:
    tags: true
    repo: bonedaddy/bettercap
